### ISSUE TITLE
Не распознается даже шаблонный текст

### ISSUE THREAD

**Issue by New4nc3** [zamgi/lingvo--classify#1]
Приветствую Вас, уважаемый автор! Я впечатлен Вашими програмными продуктами и очень хотел бы разобраться с Автоклассификатором Текста на русском. Скачал Ваш исходник, скомпилил, все прекрасно и без ошибок. Запускаемым проектом назначил classify.web.demo. После запуска и нажатия кнопки "Обработать" выдает "significant entity not found in the text", причем эта же статья на Вашем демо-сайте распознается корректно. Простите за мою наглость, но что я сделал не так? Буду признателен за помощь.
![entitty not found](https://cloud.githubusercontent.com/assets/23665859/24096144/017fa2f0-0d69-11e7-8a47-7599f5c79b2e.png)
А вот с Вашего демо-сайта:
![demolive](https://cloud.githubusercontent.com/assets/23665859/24096198/406286e0-0d69-11e7-904a-b57b7126382b.png)
P.S. Интересная штука: если запускать через IE, то все РАБОТАЕТ. 
![image](https://cloud.githubusercontent.com/assets/23665859/24200102/a50bcf6e-0f14-11e7-82c2-f55f1d308534.png)
Скажите, что не так с хромом? Или с конфигами студии? Буду очень благодарен.

**Comment by zamgi** [comment]
посмотрите, есть ли какие-то скриптовые ошибки в хроме.

**Comment by zamgi** [comment]
возможно в хроме мешает какое-то его расширение

**Comment by New4nc3** [comment]
В общем, тему можно закрывать.
Прошел отладчиком весь путь, очистил и пересобрал решение, все заработало и на хроме.
Буду переделывать под свои нужды. 
Огромное спасибо автору!
