### ISSUE TITLE
Помогите поднять в Docker

### ISSUE THREAD

**Issue by arturgspb** [zamgi/lingvo--classify#2]
Привет! На C# не рублю совсем, а надо достаточно срочно. =(
Вот думал может есть что-то готовое или что примерно запускать, чтоб собралось?

Заранее спасибо!

**Comment by New4nc3** [comment]
Привет. К сожалению нет времени, от слова, совсем. Работаю, возможно на выходных что-нибудь придумаю, но уверен, что до этого времени ты разберёшься. Удачи!

13 липня 2020, 01:04:26, від "Artur Geraschenko" <notifications@github.com>:



Привет! На C# не рублю совсем, а надо достаточно срочно. =(
Вот думал может есть что-то готовое или что примерно запускать, чтоб собралось?

Заранее спасибо!

**Comment by arturgspb** [comment]
Понимаю, постараюсь. Тикет не закрываю - а вдруг? =)

**Comment by arturgspb** [comment]
=(
